spring.application.name=spring-ai-rag-implementation

# Postgres Config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PWD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring AI OpenIA Config
spring.ai.openai.base-url=${AI_BASE_URL}
spring.ai.openai.api-key=""
spring.ai.openai.embedding.options.model=text-embedding-nomic-embed-text-v2-moe
spring.ai.openai.embedding.options.dimensions=768

spring.ai.openai.chat.base-url=${AI_BASE_URL}
spring.ai.openai.chat.api-key=""
spring.ai.openai.chat.options.model=google/gemma-3-4b

# PGvector Config
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.max-document-batch-size=10000
spring.ai.vectorstore.pgvector.schema-validation=true
spring.ai.vectorstore.pgvector.table-name=document